version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # <- externe 8080, interne 80
    environment:
      - NODE_ENV=production
    restart: unless-stopped